services:
  angular-app:
    build: ./FrontEnd
    ports:
      - "4200:80"
    volumes:
      - .:/app
    

  api:
    build: 
         context: ./backend/backend
         dockerfile: Dockerfile
    
    ports:
      - "5000:8080"
